---
title: "my blog"
date: 2020-04-19
---
title: Cookie Monster
theme: minima
author: surhub
email: saurabhsb111@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 A-Trial=Ans-Error spirit with a vivid imagination. a minimaist hobo with a little spart.
# social links
twitter_username: acookieguy # DO NOT include the @ character, or else the build will fail!
github_username:  surhub # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
